# Development properties
server:
  port: 3010

logging:
  level:
    org:
      apache:
        kafka:
          clients:
            NetworkClient: ERROR

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      properties:
#        acks: all
#    consumer:
#      group-id: main
#      auto-offset-reset: earliest
#      default-topic: general





