name: PULSE8-CORE ACCESS CONTROL BACKEND CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_REGISTRY: ghcr.io
  SVC_NAME: pulse8-core-access-control
  IMAGE_NAME: pulse8-core-access-control-${{ github.ref_name }}
  MAVEN_OPTS: -Djava.awt.headless=true
  MAVEN_CLI_OPTS: -Dmaven.repo.local=./.m2/repository --batch-mode
  AWS_REGION: ap-southeast-1
  EKS_CLUSTER_NAME: pulse8-cluster
  AWS_ROLE: arn:aws:iam::105815711361:role/github-actions-oidc-role
  SERVER_USERNAME: ${{ secrets.JFROG_USER }}
  SERVER_PASSWORD: ${{ secrets.JFROG_TOKEN }}

permissions:
  contents: read
  id-token: write

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17 and run tests
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
      - run: |
          mkdir -p .m2/repository
          du -h -d1 .m2/repository
          mvn $MAVEN_CLI_OPTS test -P ci -s ./settings.xml
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: synpulse-group/s8-actions/custom-build-push-container@main
        timeout-minutes: 30
        with:
          docker-build-context-location: .
          docker-file-path: Dockerfile
          jfrog-user: ${{ secrets.JFROG_USER }}
          jfrog-password: ${{ secrets.JFROG_TOKEN }}

